### ISSUE TITLE
Port to dotnet 6

### ISSUE THREAD

**Issue by kreghek** [Ellpeck/GameBundle#1]
Hello. The tool requires `Framework: 'Microsoft.NETCore.App', version '2.1.0' (x64)`. Can you port your tool to use only dotnet6? Currently m Monogame project uses only dotnet6. It would be cool not to install additional build dependencies.

**Comment by Ellpeck** [comment]
Yes! I've been meaning to add the `RollForward` directive ever since I did it for my other tool [Contentless](https://github.com/Ellpeck/Contentless/commit/d1012c8a28a3b515e831b27a8d7a2bb9b82abad3), but I kept forgetting. I'll probably be able to do it today :)
